info:
  profile: development
spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/mall
    username: postgres
    password: postgres
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost