info:
  profile: production
spring:
  datasource:
    url: jdbc:postgresql://db:9999/mall
    username: reader
    password: 123456
  elasticsearch:
    uris: es:9200
management:
  health:
    elasticsearch:
      response-timeout: 1000ms #加大健康检查超时时间
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: logstash
