version: '3'
services:

  mall-postgres:
    image: postgres:13.3
    container_name: mall-postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mall
    volumes:
      - ./mydata/postgres/data:/var/lib/postgresql/data
    ports:
      - "9999:5432"
    healthcheck:
      test: pg_isready -U postgres -d mall
      interval: 300s
      timeout: 10s
      retries: 5

  mall-flyway:
    image: flyway/flyway:7.11.1
    container_name: mall-flyway
    command: migrate
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/migration:/flyway/sql
    depends_on:
      - mall-postgres

  nacos-mysql:
    image: mysql:5.7
    container_name: nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - "3333:3306"
    volumes:
      - ./mydata/mysql:/var/lib/mysql
      - ./nacos:/docker-entrypoint-initdb.d/
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    command: redis-server --appendonly yes
    volumes:
      - ./mydata/redis/data:/data #数据文件挂载
      - ./mydata/redis/log:/var/log/redis/ #数据文件挂载
      - ./redis:/usr/local/etc/redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - ./mydata/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - ./mydata/nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    volumes:
      - ./mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ./mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601

  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - ./mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017

  # If mysql does not have table defined in ./nacos/init.sql.
  # Need to run ./nacos/init.sql in mysql then restart the nacos registry
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-registry
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
    ports:
      - 8848:8848
    depends_on:
      - nacos-mysql
    restart: on-failure
