spring:
  datasource:
    url: jdbc:postgresql://db:9999/mall
    username: reader
    password: 123456
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: logstash
